
#define Debug rstd_Debug
#define PrintInDebugger rstd_PrintInDebugger
#define RInvalidCodePath rstd_RInvalidCodePath
#define WarningMessageBox rstd_WarningMessageBox
#define RawAssert rstd_RawAssert
#define RAssert rstd_RAssert
#define LineName rstd_LineName
#define DebugOnly rstd_DebugOnly
#define ReleaseOnly rstd_ReleaseOnly
#define Assert rstd_Assert 
#define AssertM rstd_AssertM 
#define InvalidCodePath rstd_InvalidCodePath
#define InvalidDefaultCase rstd_InvalidDefaultCase
#define defer rstd_defer
#define generic_string rstd_generic_string
#define generic_string_view rstd_generic_string_view
#define stringlike rstd_stringlike
#define ForCString rstd_ForCString
#define AllocateArenaZero rstd_AllocateArenaZero
#define SubArena rstd_SubArena
#define PushSizeUninitialized rstd_PushSizeUninitialized
#define PushSizeZero rstd_PushSizeZero
#define PushStructUninitialized rstd_PushStructUninitialized
#define PushStructZero rstd_PushStructZero
#define PushArrayUninitialized rstd_PushArrayUninitialized
#define PushArrayZero rstd_PushArrayZero
#define PushStringCopy rstd_PushStringCopy
#define For rstd_For
#define ForF32 rstd_ForF32
#define ArrayCount rstd_ArrayCount
#define ScopeLock rstd_ScopeLock